server.port: 8080
spring:
  application.name: template-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/manugen}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari.schema: ${DB_SCHEMA:templates}
  jpa:
    hibernate.ddl-auto: none
    show-sql: false
    properties.hibernate:
        format_sql: true
        default_schema: ${DB_SCHEMA:templates}
  security.oauth2:
      client.exchange:
        yandex:
          exchange-url: https://oauth.yandex.ru/token
          client-id: ${YANDEX_CLIENT_ID:yandex-client-id}
          client-secret: ${YANDEX_CLIENT_SECRET:yandex-client-secret}
          redirect-uri: ${YANDEX_REDIRECT_URI:http://localhost:3000}
      resourceserver:
        opaquetoken:
          introspection-uri: https://login.yandex.ru/info?format=json
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB